# Generated by Django 5.0.1 on 2024-12-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tycdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_part', models.CharField(max_length=255)),
                ('te_internal_number', models.CharField(max_length=255)),
                ('part_status', models.CharField(max_length=255)),
                ('rohs_compliant_status', models.CharField(max_length=255)),
                ('rohs_exemption_substance_info', models.TextField()),
                ('reach_version_status', models.CharField(max_length=255)),
                ('reach_compliant_status', models.CharField(max_length=255)),
                ('reach_svhc_substance', models.TextField()),
            ],
        ),
    ]
